ch: setup readme file
atlp-rwanda/matadors-rn-medica pull request #10
Opened 2024-04-30 12:37 UTC by Paccyfic

What does this PR do?
This PR adds a structured README.md file for the Medica app project . The README includes a detailed description of the app, setup instructions, endpoints documentation, and contribution guidelines.

Description :
-Created a README.md file .
-Added sections for project description, documentation, setup instructions, testing, contribution guidelines, and deployment.
-Included placeholders for badges, endpoints, dependencies, and testing instructions.

 Review it and feel free to merge it to the main branch .Your feedback is appreciated!

2024-04-30 14:06 UTC, mr3nz1 approved these changes

2024-04-30 14:58 UTC, Nkbtemmy requested changes

2024-04-30 14:58 UTC, Nkbtemmy commented on README.md
> +Url;
This is not needed

2024-04-30 14:58 UTC, Nkbtemmy commented on README.md
> +npm install
Highlight this command

2024-04-30 14:58 UTC, Nkbtemmy commented on README.md
> +npm start
Again this one

2024-04-30 14:58 UTC, Nkbtemmy commented on README.md
> +None at the moment.
This is not needed

2024-04-30 14:58 UTC, Nkbtemmy commented on README.md
> +npm test
Also this one highlight it

2024-04-30 14:58 UTC, Nkbtemmy commented on README.md
> +4. Push to the branch (`git push origin feature/my-feature`).
Please make sure your branches are created as you said.

2024-04-30 14:58 UTC, Nkbtemmy commented on README.md
> +3. [Step 3 for deployment]
Remove this ones

2024-04-30 14:58 UTC, Nkbtemmy commented on README.md
> +  None At the moment !!
Better put your contributors list here including your manager and TTL

2024-05-01 09:58 UTC, Paccyfic commented on README.md
> +  None At the moment !!
you mean on the contacts ..??

2024-05-01 14:40 UTC, Nkbtemmy approved these changes

2024-05-01 14:40 UTC, merged