Enhance Notification screen UI and Dark theme
atlp-rwanda/matadors-rn-medica pull request #105
Opened 2024-05-29 10:03 UTC by 23nosurrend

### What does this PR do?
Enhance UI and Add Dark Theme for Notification Screen

### Description:

This PR focuses on enhancing the UI and adding a dark theme to the Notification Screen. The current implementation has several issues that need to be addressed to ensure a seamless and aesthetically pleasing user experience. The specific areas that require attention include:

#### Dynamic Theme Handling:
 Ensure that the background color and other UI elements adjust dynamically based on the selected theme (light or dark).
Notification Layout: Improve the layout and appearance of notification items for better readability and visual appeal.
Tasks:

#### Dynamic Theme Handling:

Ensure that all notification items are well-organized and visually appealing.
Check for any overlapping text or UI elements and resolve them.
Improve the layout for better readability.
Theme-Specific Adjustments:

Light Theme: Ensure that the background and text colors provide sufficient contrast for readability.
Dark Theme: Apply dark background colors and light text colors for better visibility in low-light conditions.
Adjust icon colors to ensure they are clearly visible in both themes.

### Screenshot
![Screenshot_20240529_114043_Expo Go](https://github.com/atlp-rwanda/matadors-rn-medica/assets/102511280/d48965a5-7a1e-4bab-9864-0ff9bde8bc81)

2024-05-29 13:41 UTC, Paccyfic approved these changes
perfect..!!

2024-05-31 05:37 UTC, mr3nz1 approved these changes

2024-05-31 09:46 UTC, Nkbtemmy requested changes

2024-05-31 09:46 UTC, Nkbtemmy commented on .env
> +EXPO_PUBLIC_API_KEY=abc123
Don't push .env file

2024-05-31 09:58 UTC, Nkbtemmy approved these changes

2024-05-31 09:58 UTC, merged