Fix oboarding dark theme and setup profile
atlp-rwanda/matadors-rn-medica pull request #113
Opened 2024-05-30 10:56 UTC by mr3nz1

### What does this pull request do?

Fixes design issues with and adds dark mode to the first, second screen and setup profile screens

### Description

- [x] First screen after splash screen
- [x] Home screen
- [x] Your profile screen
- [x] Dark theme

### Description

<div style="display: flex; flex-wrap: wrap;">
<img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/ef08e598-7544-4926-8d3f-adfe110be426" height="480px" />
<img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/4513dc45-1bdb-467b-962b-be0b04e73425" height="480px" />
<img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/f4b131d1-014e-4454-81bd-b78c380f5931" height="480px" />
<img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/49891b70-13bf-45a3-aaae-699e289f855b" height="480px" />
<img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/1a9c3dc2-64c5-43ed-8546-3572625b3d64" height="480px" />
<img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/7c8bdf34-3fa2-43e4-bd4a-396e24e91bc3" height="480px" />
</div>

2024-05-30 14:17 UTC, Paccyfic approved these changes
great dark theme implementations..!!

2024-05-31 05:34 UTC, Paccyfic approved these changes
just noticed a small typing error on your PR's title..!!..😂😂

2024-05-31 05:39 UTC, Irirwanirira approved these changes
Good Job

2024-05-31 07:50 UTC, Nkbtemmy requested changes

2024-05-31 07:50 UTC, Nkbtemmy commented on .env
> +EXPO_PUBLIC_API_KEY=abc123
Never push .env file; create .env.example to provide a reference

2024-05-31 07:55 UTC, mr3nz1 commented on .env
> +EXPO_PUBLIC_API_KEY=abc123
Let  me make sure to

2024-05-31 08:45 UTC, Nkbtemmy approved these changes

2024-05-31 08:46 UTC, merged