fix: book and reschedule appointment screen
atlp-rwanda/matadors-rn-medica pull request #121
Opened 2024-06-03 12:54 UTC by aimeudoxie

### Title: Fixing book and rescheduler appointment screen

## Description:
This pull request fixes the calendar components on book and reschedule appointment screen where now it is possible to select date and hour this pull request also implements dark mode of these screens

## Task completed 
- [x] book appointment calendar screen enhancement
- [x] reschedule appointment calendar screen enhancement

## Screenshots

![image](https://github.com/atlp-rwanda/matadors-rn-medica/assets/98123621/95d23724-1397-43df-9e3c-036bcd440e57)

![image](https://github.com/atlp-rwanda/matadors-rn-medica/assets/98123621/55a19416-1a10-4388-a975-ca4a14e650d5)

2024-06-05 12:52 UTC, Irirwanirira approved these changes
Good Job

2024-06-05 13:40 UTC, Paccyfic approved these changes

2024-06-05 13:54 UTC, Nkbtemmy requested changes

2024-06-05 13:54 UTC, Nkbtemmy commented on app/(app)/ActionMenu/Booking/BookingAppointment.tsx
> +              style={[Typography.heading._4,{color:theme === 'light'? Colors.grayScale._900: Colors.others.white}]}
Remove this commented codes

2024-06-06 08:27 UTC, Nkbtemmy approved these changes

2024-06-06 08:27 UTC, merged