Refactor: Reusable components
atlp-rwanda/matadors-rn-medica pull request #136
Opened 2024-06-11 12:05 UTC by mr3nz1

### What does this pull request do?
Gives reusable components

![Screenshot_1718086487](https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/fc6f37d0-e4d2-41e5-9e20-3e4e958665cc)
![Screenshot_1718086458](https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/58362af6-3a04-46cf-839d-69f31044bfa3)
![Screenshot_1718086479](https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/b79b2553-964e-4eed-9bfe-686420d33417)

2024-06-13 21:26 UTC, Irirwanirira approved these changes
Good job

2024-06-13 21:26 UTC, Irirwanirira approved these changes

2024-06-14 07:15 UTC, munezeromicha approved these changes

2024-06-14 10:19 UTC, Nkbtemmy requested changes

2024-06-14 10:19 UTC, Nkbtemmy commented on components/UI/DatePicker.tsx
> +
Remove this commented codes

2024-06-14 10:19 UTC, Nkbtemmy commented on components/UI/DropDown.tsx
> +          // borderColor: theme === "light" ? Colors.others.white : Colors.others.
Even this small ones

2024-06-14 10:27 UTC, 23nosurrend approved these changes

2024-06-14 10:39 UTC, Nkbtemmy approved these changes

2024-06-14 10:39 UTC, merged