Chore: Auth Context
atlp-rwanda/matadors-rn-medica pull request #141
Opened 2024-06-12 07:03 UTC by mr3nz1

### What does this pull request do?
This PR provides a global way to keep track of whether the user is logged in or not

### Description
It keeps track of the following

- [x] Auth token
- [x] Refresh token
- [x] user logged in

2024-06-12 07:45 UTC, Irirwanirira approved these changes
Good job

2024-06-14 08:27 UTC, 23nosurrend requested changes

2024-06-14 08:27 UTC, 23nosurrend commented on app/(app)/ActionMenu/index.tsx
> +  import {} useConte
consider fixing this ,import should be used at the beginning

2024-06-14 09:28 UTC, 23nosurrend approved these changes

2024-06-14 09:37 UTC, Nkbtemmy requested changes

2024-06-14 09:37 UTC, Nkbtemmy commented on app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
> +  // }
Don't push commented codes

2024-06-14 09:37 UTC, Nkbtemmy commented on ctx/AuthContext.tsx
> +        // Alert.alert(error.message);
Remove even this small comments

2024-06-20 11:42 UTC, closed without merging