Facebook Login Integration in Medica App
atlp-rwanda/matadors-rn-medica pull request #149
Opened 2024-06-13 11:54 UTC by munezeromicha

**Summary**

This pull request introduces the feature for logging in with Facebook in our Medica app, which is developed using React Native and TypeScript. The integration is powered by Supabase, ensuring a smooth and secure authentication process.

**Features Implemented**

**Supabase Authentication:**

- Configured Supabase to handle OAuth authentication with Facebook.
- Implemented necessary API calls for the login process.

**User Session Management:**

- Integrated session management to handle user sessions post-login.
- Stored user session data securely using Supabase's session handling mechanisms.

**Technical Details**

**React Native:**

- Used `npm i react-native-fbsdk-next` library for Facebook login integration.

**Supabase:**

- Configured Supabase project to include Facebook as an authentication provider.

**ScreenShoots:**

<div style="display: flex; flex-wrap: wrap;">
    <img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/126547244/5e850c10-ab50-45d6-9f0c-dc64daee2076" alt="Screenshot 1" height="480px">
    <img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/126547244/763c6c21-c26e-4bd7-9fd4-bef0862e1266" alt="Screenshot 2" height="480px">
</div>

2024-06-17 05:40 UTC, Irirwanirira approved these changes
Good job

2024-06-17 07:47 UTC, mr3nz1 approved these changes

2024-06-17 21:07 UTC, Nkbtemmy requested changes
make sure you pushed only necessary files so check androd folder and .vscode !!

2024-06-18 08:19 UTC, Nkbtemmy approved these changes

2024-06-18 08:19 UTC, merged