Chore: Add GitHub Actions Workflows for Continuous Integration
atlp-rwanda/matadors-rn-medica pull request #17
Opened 2024-05-02 07:39 UTC by 23nosurrend

## What does this PR do?

This pull request introduces two new GitHub Actions workflows to automate the testing process for both push and pull request events. These workflows are essential for ensuring code quality and functionality before changes are merged into the main branch.

## Description of Workflows Added

1. **Push Trigger Workflow (`push.yml`)**:
   - **Trigger**: Activates on any push to any branch in the repository.
   - **Purpose**: Ensures that every push to the repository, regardless of the branch, passes all configured tests.
   - **Steps Executed**:
     - Checkout the code.
     - Set up the Node.js environment.
     - Install all necessary dependencies.
     - Execute the test suite using `npm run test -- --ci`.

2. **Pull Request Trigger Workflow (`pull_request.yml`)**:
   - **Trigger**: Activates on pull requests targeted at the `develop` branch.
   - **Purpose**: Makes sure that changes in pull requests are tested against the develop branch before they are merged.
   - **Steps Executed**:
     - Checkout the code.
     - Set up the Node.js environment.
     - Install all necessary dependencies.
     - Execute the test suite to validate changes.

## How should this be manually tested?

To verify the functionality of these workflows:
- **For Pushes**: Make a commit and push it to any branch. Navigate to the "Actions" tab in GitHub and observe if the "Push Trigger Workflow" executes and passes all the steps.
- **For Pull Requests**: Open a pull request to `develop`. Watch the "Actions" tab to see if the "Pull Request Trigger Workflow" runs and successfully completes all steps.

## Any background context you want to provide?

Implementing these workflows automates our testing process, reducing the need for manual checks and helping maintain code quality through automated, consistent testing procedures. This integration into our CI/CD pipeline aligns with our objectives to improve development practices and ensure reliable software delivery.

2024-05-02 10:24 UTC, mr3nz1 approved these changes

2024-05-02 17:24 UTC, Nkbtemmy requested changes
Just work on your commits(Squash them into one)

2024-05-02 21:05 UTC, mr3nz1 approved these changes

2024-05-03 09:44 UTC, Irirwanirira approved these changes

2024-05-03 09:51 UTC, Nkbtemmy approved these changes

2024-05-03 09:52 UTC, merged