Refine Appointment Booking: Add Form Validation and Duration-Based Amount Calculation
atlp-rwanda/matadors-rn-medica pull request #207
Opened 2024-07-10 12:49 UTC by 23nosurrend

### What does this pull request do?
Refines the appointment booking process by adding form validation handlers to ensure all required data is selected before navigation and introduces a duration variable to calculate the total amount.

### Description
Implemented the following functionalities:

- [ ] Form Validation Handlers: Ensured users cannot navigate to the next screen without selecting each required piece of information (gender, age, and problem description). This prevents incomplete data from being submitted and enhances user experience.

- [ ] Duration Variable for Amount Calculation: Added a variable to capture the duration a patient has selected. This duration is now used to accurately calculate the total amount for the appointment, ensuring that users are aware of the cost based on the duration of their selected appointment.

- [ ] Supabase Integration: The selected data (gender, age, problem description, and duration) is managed and stored through Supabase, maintaining consistency and reliability in the appointment booking process.

### Screenshots

![Screenshot_20240710_144720_Expo Go](https://github.com/atlp-rwanda/matadors-rn-medica/assets/102511280/433f4c63-7fcc-42ea-b2d8-14974fa25603)
![Screenshot_20240710_144658_Expo Go](https://github.com/atlp-rwanda/matadors-rn-medica/assets/102511280/2b4777b3-f11a-4f34-b60c-ce89a796060d)

2024-07-10 13:45 UTC, Irirwanirira requested changes
Good job on implementing all this work, but below are some changes requested, kindly refer to the comments below and re-request a review after working in them. 

-  After the user presses on the success button in the modal he is redirected to the lists of appointments which is very good but whenever he gets back to the home screen ... they give him a page to add his pin again which triggers the modal for the second time. and from here a user can book multiple appointments at once.  please work on that.

2024-07-10 13:45 UTC, Irirwanirira commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
> +
Remove these console.log to have a clean code base.

2024-07-10 13:45 UTC, Irirwanirira commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
> +  console.log("this is default value:",profile?.gender,profile?.age)
same here, they may be for testing purpose but not good on develop

2024-07-10 13:45 UTC, Irirwanirira commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
>            />
kindly for the user experience as we are fetching data form the data base and they don't need to be edited at this stage consider displaying them in the <Text> tag or disable <Input>

2024-07-10 13:45 UTC, Irirwanirira commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
> +
Kindly consider displaying the following not in the Drop down

2024-07-10 13:45 UTC, Irirwanirira commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
> +            // }}
Kindly remove the commented code to have a clean codebase

2024-07-11 11:01 UTC, 23nosurrend commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
> +
Done

2024-07-11 11:01 UTC, 23nosurrend commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
> +  console.log("this is default value:",profile?.gender,profile?.age)
Done

2024-07-11 11:01 UTC, 23nosurrend commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
>            />
Done

2024-07-11 11:02 UTC, 23nosurrend commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
> +
Done

2024-07-11 11:02 UTC, 23nosurrend commented on app/(app)/ActionMenu/Booking/Patient-details.tsx
> +            // }}
Done

2024-07-11 13:24 UTC, munezeromicha approved these changes

2024-07-11 13:34 UTC, mr3nz1 approved these changes

2024-07-11 13:50 UTC, Nkbtemmy approved these changes

2024-07-11 13:50 UTC, merged