Implement Doctor's ratings and review feature
atlp-rwanda/matadors-rn-medica pull request #211
Opened 2024-07-11 23:20 UTC by aimeudoxie

## What this PR do
This pull request implements the functionality that  allows Users to  give reviews to doctors , users chooses the number of rate stars, the review message and if they can recommend that doctor or not.
those reviews sent by user are displayed on doctors' profiles and anyone is allowed to view them and like them 

## Detailed features implemented

- [x] Adding review to a certain doctor after consultation session
- [x] Displaying reviews on Doctors' profiles
- [x] review liking
- [x] filtering reviews according to rates

## Screenshots
![Screenshot 2024-07-12 010338](https://github.com/user-attachments/assets/6266ddce-45e3-4360-b508-c0aa2e5a3f10)
![Screenshot 2024-07-12 010413](https://github.com/user-attachments/assets/ab22aa10-5333-4d51-bd01-755fb7955c75)

2024-07-15 06:49 UTC, Irirwanirira approved these changes
Good Job on Implementing the following

2024-07-15 07:53 UTC, Irirwanirira requested changes
KIndly make sure that different users are able to give a review.

2024-07-15 12:58 UTC, Irirwanirira approved these changes
Good Job

2024-07-15 19:49 UTC, munezeromicha approved these changes

2024-07-16 08:27 UTC, Nkbtemmy approved these changes

2024-07-16 08:27 UTC, merged