Feature: Fingerprint and Alert Modal
atlp-rwanda/matadors-rn-medica pull request #22
Opened 2024-05-03 13:45 UTC by mr3nz1

### What does this pull request do?
This pull request has fingerprint authentication and an alert modal 

### Description
- Fingerprint screen
- Fingerprint alert modal

### Screenshots
<div style="display: flex; flex-wrap: wrap;">
    <img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/c255ee8e-6e88-4652-91d0-040c4f7339d8" alt="Screenshot 1" height="480px">
    <img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/620a828b-52d8-40e7-874d-ed1c99dc5d53" alt="Screenshot 2" height="480px">
    <img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/44da3ee5-87a0-4a5a-9d64-c5cbaee4d263" alt="Screenshot 3" height="480px">
    <img src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/88678347/ec6fbf31-4c7a-4342-9744-294852983c16" alt="Screenshot 4" height="480px">
</div>

2024-05-05 17:28 UTC, Irirwanirira requested changes
Solve your conflicts with develop

2024-05-06 12:46 UTC, Irirwanirira approved these changes
Good Job on implementing all these changes

2024-05-06 12:48 UTC, Nkbtemmy approved these changes

2024-05-06 12:51 UTC, Nkbtemmy commented
Please make sure you setup correctly your PR 
![image](https://github.com/atlp-rwanda/matadors-rn-medica/assets/41394162/48e02542-2cfa-439a-9b62-b45db2b17f3f)

2024-05-06 12:55 UTC, merged