chore(github-actions): create update.yml and add code coverage config…
atlp-rwanda/matadors-rn-medica pull request #23
Opened 2024-05-05 08:38 UTC by 23nosurrend

# What does this PR do?

This pull request introduces four new GitHub Actions workflows to automate the testing, building, and coverage reporting processes. These workflows are essential for maintaining high code quality, ensuring functionality before changes are merged, and providing insights into test coverage.

# Description of Workflows Added
## Push Trigger Workflow (push.yml)

- Trigger: Activates on any push to any branch in the repository.

- Purpose: Ensures that every push, regardless of the branch, passes all configured tests.

### Steps Executed:

- Checkout the code.

- Set up the Node.js environment.

- Install all necessary dependencies.

- Execute the test suite using npm run test -- --ci.

## Pull Request Trigger Workflow (pull_request.yml)

- Trigger: Activates on pull requests targeted at the develop branch.

- Purpose: Ensures that changes in pull requests are tested against the develop branch before they are merged.

- Steps Executed:

- Checkout the code.

- Set up the Node.js environment.

- Install all necessary dependencies.

- Execute the test suite to validate changes.

## App Build Workflow (update.yml)

- Trigger: Activates on merges to the main branch.

- Purpose: Automates the building of the application and generates an AAB file, preparing it for deployment or further testing.

- Steps Executed:

- Checkout the code.

- Set up the Node.js environment.

- Install all necessary dependencies.

- Build the app using npm run build, generating an AAB file.

## Code Coverage Workflow (codecov.yml)

- Trigger: Activates alongside the push and pull request workflows.

- Purpose: Generates and updates code coverage reports on Codecov, providing visibility into the test effectiveness and areas needing more coverage.

- Steps Executed:

- After tests are run, upload the coverage report to Codecov using the codecov action.

- How should this be manually tested?

- To verify the functionality of these workflows:

### For Pushes: 

- Make a commit and push it to any branch. Navigate to the "Actions" tab in GitHub and observe if the "Push Trigger Workflow" and "Code Coverage Workflow" execute and pass all steps.

### For Pull Requests:

-  Open a pull request to develop. Watch the "Actions" tab to see if the "Pull Request Trigger Workflow" and "Code Coverage Workflow" run and successfully complete all steps.

### For Merges to Main: 

- Merge changes into the main branch and check if the "App Build Workflow" correctly generates the AAB file and if the "Code Coverage Workflow" provides updated coverage metrics.

# Any background context you want to provide?
Implementing these workflows automates our testing and building process, enhances our CI/CD pipeline, and integrates systematic code coverage analysis. This automation not only reduces the need for manual checks but also helps maintain consistent testing procedures, streamlines build operations, and provides crucial data on code quality and test coverage. This strategic enhancement aligns with our goals to bolster development practices and ensure reliable, efficient software delivery.

2024-05-05 09:04 UTC, mr3nz1 approved these changes

2024-05-05 10:04 UTC, Irirwanirira approved these changes
Good Job

2024-05-06 08:22 UTC, Nkbtemmy requested changes
please put coverage folder in gitignore; No need for it to be pushed

2024-05-06 15:21 UTC, Nkbtemmy approved these changes

2024-05-06 15:22 UTC, merged