Ft signup your profile
atlp-rwanda/matadors-rn-medica pull request #26
Opened 2024-05-05 20:35 UTC by Mbabazi12

### What does this PR do
This PR consist of two pages
1. Your Profile Page
2. Create New Pin Page
### Description for this PR
For Your profile screen it consist of the form where you can create your profile and even add the image if you want,
Also Create new Pin is there for helping a user to create a new whenever he/she wants.

### Screenshots:

![createNewPin Screen](https://github.com/atlp-rwanda/matadors-rn-medica/assets/147439113/433c60a2-3ab4-43a7-8bbe-04e81fff68a1)
![yourProfileScreen](https://github.com/atlp-rwanda/matadors-rn-medica/assets/147439113/39772c3a-0a45-4e21-9d48-f5b342e9839a)

2024-05-06 14:12 UTC, Nkbtemmy commented
Please do setup well your PR; by requesting reviewers; assign to project and milestone as well !!

2024-05-06 21:33 UTC, Irirwanirira requested changes
Good job on implementing all these changes. but kindly fix the presented conflicts to be able to merge on develop.

2024-05-07 11:30 UTC, mr3nz1 approved these changes

2024-05-07 11:30 UTC, Irirwanirira approved these changes
Good job

2024-05-07 12:18 UTC, Nkbtemmy approved these changes

2024-05-07 12:18 UTC, merged