Feature: Forget Password and OTP verification
atlp-rwanda/matadors-rn-medica pull request #27
Opened 2024-05-06 00:47 UTC by aimeudoxie

**What this PR does**
This pull request contains the implementation of forget password and OTP verification screen

**Description**
**Forget password screen**
In this feature a user will be able to select an method that will be used to send the reset password code either by email or by phone.
This is implemented in both light and dark mode
![Screenshot 2024-05-06 020815](https://github.com/atlp-rwanda/matadors-rn-medica/assets/98123621/72e84020-77a0-41f8-b49d-0c1cfb4e4051)
![Screenshot 2024-05-06 020852](https://github.com/atlp-rwanda/matadors-rn-medica/assets/98123621/ec58e97e-20a7-4f6b-9569-2f683ce66123)

**OTP verification screen**
For the user that have chosen to receive the reset code through Phone this feature will help to enter the Reset code sent to his/her phone for it to be verified
This is implemented in both light and dark mode
![Screenshot 2024-05-06 021010](https://github.com/atlp-rwanda/matadors-rn-medica/assets/98123621/acdc0d92-6000-40c2-8a67-1568c446457e)
![Screenshot 2024-05-06 021055](https://github.com/atlp-rwanda/matadors-rn-medica/assets/98123621/64a6bea4-1925-4589-bf66-45e98e078c6b)

2024-05-06 15:29 UTC, Irirwanirira requested changes
Good job so far, but you still have some conflicts to resolve !!

2024-05-07 14:03 UTC, Irirwanirira approved these changes
Great job

2024-05-07 15:11 UTC, Nkbtemmy requested changes

2024-05-07 15:11 UTC, Nkbtemmy commented on README.md
> +>>>>>>> 0cf82c1b70117e205e437bb58220f0ef9ad30984
Even here

2024-05-07 15:11 UTC, Nkbtemmy commented on README.md
This indicates that you still have conflicts

2024-05-07 15:11 UTC, Nkbtemmy commented on components/UI/Header.tsx
> +>>>>>>> a304d8c (ft(auth): adding-forgetPassword-OTPverification)
This also indicates that you still have resolved conflicts not correctly

2024-05-07 15:11 UTC, Nkbtemmy commented on components/UI/icons.tsx
> +>>>>>>> a304d8c (ft(auth): adding-forgetPassword-OTPverification)
Please resolve your conflict correctly

2024-05-07 15:11 UTC, Nkbtemmy commented on constants/Colors.ts
>    //   gradient_orange: { from: { x: 0, y: 0 }, to: { x: 1, y: 1 }, color: [""] },
Delete commented codes; in case you aren't using them

2024-05-08 10:12 UTC, closed without merging