Feature: Add Scheduled Appointments Components
atlp-rwanda/matadors-rn-medica pull request #88
Opened 2024-05-22 00:27 UTC by Paccyfic

###What does this PR do?
This PR introduces new screens for managing scheduled appointments within the Medica app, enhancing the appointment management system.

###Description:

- [ ] Implemented Cancelled Appointments Screen to display past cancelled appointments.
- [ ]  Developed Upcoming Appointments Screen allowing users to reschedule or cancel appointments.
- [ ]  Created Empty Upcoming Appointments Screen to provide guidance when no appointments are scheduled.
- [ ]  Designed Completed Appointments Screen to showcase past appointments and enable rebooking and reviews.

###Changes Made:

1. Implemented navigation logic for seamless transition between appointment screens.
2. Ensured consistent styling and UI/UX patterns across all appointment screens for a cohesive user experience.

###Screenshots:
<img width="293" alt="Screenshot 2024-05-22 at 01 52 02" src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/147504934/cf8801eb-712f-4092-9545-7edb7977ae44">
<img width="293" alt="Screenshot 2024-05-22 at 01 52 29" src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/147504934/b7701fea-c55e-4efb-b09e-2442ede84adc">
<img width="293" alt="Screenshot 2024-05-22 at 01 52 46" src="https://github.com/atlp-rwanda/matadors-rn-medica/assets/147504934/1e3a1147-a62d-4270-bd0c-2085b33609d9">

Please review this PR and provide feedback. Once approved, it can be merged into the develop branch.

2024-05-22 06:38 UTC, 23nosurrend requested changes
Good Job !

But on the last screenshot , the card which represent completed appointment has big padding bottom! Kindly consider to see those styles which may be modified to achieve real design.

2024-05-23 08:36 UTC, 23nosurrend approved these changes

2024-05-23 08:40 UTC, Irirwanirira approved these changes
Good job

2024-05-23 08:42 UTC, Nkbtemmy approved these changes

2024-05-23 08:42 UTC, merged

2024-05-23 10:15 UTC, Irirwanirira approved these changes
Good job